<a href="https://colab.research.google.com/github/priya606/Assignment-7/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1. Numpy stands for?


In [ ]:
Numpy is python library which contains multi-dimension arrays.It is mainly used for visualising the data can be performed many operations like (arange,zeroes,random,linspace etc)


In [ ]:
3. What will be output for the
following code?


In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3], dtype =complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a = np.array([1, 2, 3], dtype ="float")
print(a)

[1. 2. 3.]


In [ ]:
a = np.dtype('i4')
print(a)

int32


In [ ]:
a = np.array([1, 2, 3,4,5], ndmin= 2)
print(a)

[[1 2 3 4 5]]


In [ ]:
dt = np.dtype([(‘age’,np.int8)])
a = np.array([(10,),(20,),(30,)],
dtype = dt)
print a[‘age’]

SyntaxError: ignored

In [ ]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c = c*a
print (c[2])

21


In [ ]:
a = np.array([1,2,3,5,8])
a = a + 1
print (a[1])

3


In [ ]:
a = np.array([[1,2,3],[0,1,4]])
print (a.size)

6


In [ ]:
a = np.array([1,2,3,5,8])
print (a.ndim)

1


In [ ]:
a = np.array([1,2,3,5,8])
print (a.ndim)
print (a.ndim.describe)
print (a.describe)
print (a.shape())
print (a.shape)

1


AttributeError: ignored

In [ ]:
print(a.shape())

TypeError: ignored

In [ ]:
print(a.shape)

(5,)


In [ ]:
a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)
d = a + b + c

In [ ]:
print (d[1,2])

5


In [ ]:
print (d.size)

6


In [ ]:
print (d.attributes)

AttributeError: ignored

In [ ]:
print (a.zeroes())

AttributeError: ignored

In [ ]:
4. You have a matrix defined as
below:

Find its - rank, determinant, trace,
inverse, transpose.

In [ ]:
A = np.array([[6, 1, 1],
[4, -2, 5],
[2, 8, 7]])

In [ ]:
print(A)
B=np.linalg.matrix_rank(A)
print(f'the rank of matrix is: {B}')

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
the rank of matrix is:3


In [ ]:
print(A)
determinant=np.linalg.det(A)
print(f'determinant of matrix is:{determinant}')

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
determinant of matrix is:-306.0


In [ ]:
print(A)
trace=np.trace(A)
print(trace)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
11


In [ ]:
print(A)
inverse=np.linalg.inv(A)
print(f'inverse of matrix is {inverse}')

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
inverse of matrix is [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [ ]:
print(A)
transpose=np.matrix.transpose(A)
print(f'transposeof matrix is:{transpose}')

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
transposeof matrix is:[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [ ]:
5. Type these lines of code and check
the output for each of them.

In [ ]:
list1 = [1, 2, 3, 4 ,5, 6]
list2 = [10, 9, 8, 7, 6, 5]

In [ ]:
print(list1*list2)

TypeError: ignored

In [ ]:
print(list1+list2)

[1, 2, 3, 4, 5, 6, 10, 9, 8, 7, 6, 5]


In [ ]:
print(list1%list2)

TypeError: ignored

In [ ]:
print(list1/list2)

TypeError: ignored

In [ ]:
print(list1-list2)

TypeError: ignored

In [ ]:
print(list1^list2)

TypeError: ignored

In [ ]:
6. Type these lines of code and check the output for each of them.

In [ ]:
list1 = np.array([1, 2, 3, 4 ,5, 6])
list2 = np.array([10, 9, 8, 7, 6, 5])

In [ ]:
print(list1*list2)

[10 18 24 28 30 30]


In [ ]:
print(list1+list2)

[11 11 11 11 11 11]


In [ ]:
print(list1%list2)

[1 2 3 4 5 1]


In [ ]:
print(list1/list2)

[0.1        0.22222222 0.375      0.57142857 0.83333333 1.2       ]


In [ ]:
print(list1-list2)

[-9 -7 -5 -3 -1  1]


In [ ]:
print(list1^list2)

[11 11 11  3  3  3]
